feat(elasticache): add ElastiCache Serverless nuking
ekristen/aws-nuke pull request #256
Opened 2024-08-24 04:19 UTC by Petersoj

2024-08-24 04:23 UTC, Petersoj commented
Will fix to pass tests tomorrow morning.

2024-08-24 17:11 UTC, Petersoj commented
I removed tag listings for serverless caches since AWS throws when attempting to query the tags of a serverless cache that doesn't currently have the "available" status.

2024-08-24 17:20 UTC, ekristen commented
I'm wondering if this should be its own resource. Looking at it on mobile, will look from my laptop soon.

2024-08-25 02:41 UTC, Petersoj commented
I suppose it could be, but I think of serverless and provisioned/on-demand clusters as essentially the same resource in this context. Similar to how RDS also has serverless and provisioned/on-demand instances in a cluster.

Also, thoughts on removing the "memcache" name from the file since ElastiCache supports both Memcached and Redis OSS and the SDK calls don't differentiate between the cache type? Just a minor detail.

2024-08-25 15:27 UTC, ekristen requested changes
@Petersoj I reviewed this based on everything I would do if I were updating this or touching this to make updates. 

I agree it should stay the same resource after looking at the UI/API and how they are distinguished. There is an argument for making them separate but for now I think they can remain the same.

If you'd prefer I can just do a commit over top of your changes already, or if you'd like to take a stab. 

I did everything in suggestion format to make it a bit easier on you. Let me know.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +			clusterID:  cacheCluster.CacheClusterId,
```suggestion
			ClusterID:  cacheCluster.CacheClusterId,
```

Reason: libnuke now has this automatic properties generator based on the resource struct.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +			status:     cacheCluster.CacheClusterStatus,
```suggestion
			Status:     cacheCluster.CacheClusterStatus,
```

Reason: libnuke now has this automatic properties generator based on the resource struct.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +			serverless: false,
Just remove this line here.

Reason: by default it is false.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +	clusterID  *string
```suggestion
	ClusterID  *string
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +	status     *string
```suggestion
	Status     *string
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +	serverless bool
```suggestion
	Serverless bool
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
>  	return properties
```suggestion
	return types.NewPropertiesFromStruct(i)
```

TODO: remove everything else from the Properties() method.

Reason: libnuke now has this automatic properties generator based on the resource struct.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
>  func (i *ElasticacheCacheCluster) Properties() types.Properties {
```suggestion
func (r *ElasticacheCacheCluster) Properties() types.Properties {
```

Reason: standardizing all pointers for resources to `r`

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +			clusterID:  serverlessCache.ServerlessCacheName,
```suggestion
			ClusterID:  serverlessCache.ServerlessCacheName,
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +			status:     serverlessCache.Status,
```suggestion
			Status:     serverlessCache.Status,
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +			serverless: true,
```suggestion
			Serverless: true,
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
>  func (i *ElasticacheCacheCluster) Remove(_ context.Context) error {
If would change this to the following:

if serverless return DeleteServerlessCacheInput

drop the else 

and then run the deleteCacheCluster

A bit cleaner this way.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters_mock_test.go
> +		clusterID:  aws.String("foobar"),
```suggestion
		ClusterID:  aws.String("foobar"),
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters_mock_test.go
> +		serverless: false,
```suggestion
		Serverless: false,
```

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
> +	for _, serverlessCache := range serverlessResp.ServerlessCaches {
You need to list tags for serverless too.

2024-08-25 15:27 UTC, ekristen commented on resources/elasticache-memcacheclusters.go
>  func (i *ElasticacheCacheCluster) Remove(_ context.Context) error {
```suggestion
func (r *ElasticacheCacheCluster) Remove(_ context.Context) error {
```

2024-08-25 15:44 UTC, Petersoj commented
@ekristen Thank you for the comprehensive review! Feel free to commit those changes in my PR, along with any other changes you see fit. I agree with all your comments. I have pretty much zero experience in Go haha so I appreciate you taking time to give me an in-depth review.

Regarding the tags issue, I observed that AWS throws when querying the tags after initiating the deletion process. Querying the tags during the "available" state is no problem. So putting in a guard to check for the "available" state when querying the tags seems appropriate as this would still allow for users to filter based on those tags during the initial listings iirc. According to the [docs](https://docs.aws.amazon.com/AmazonElastiCache/latest/APIReference/API_ServerlessCache.html), there are the following states:
> CREATING, AVAILABLE, DELETING, CREATE-FAILED and MODIFYING

2024-08-26 16:37 UTC, Petersoj commented
Did some manual testing and discovered the following API behavior of AWS when querying tags of a serverless ElastiCache cluster in various states:
| Status | `listTagsForResource` call result (via Java SDK) |
|--------|--------|
| `CREATING` | InvalidServerlessCacheStateException: Serverless cache is not in an available state to perform the requested action. (Service: ElastiCache, Status Code: 400, Request ID: a0f227b9-f956-44ae-b5de-e08be3233b87) |
| `AVAILABLE` | Success |
| `DELETING` | InvalidServerlessCacheStateException: Serverless cache is not in an available state to perform the requested action. (Service: ElastiCache, Status Code: 400, Request ID: 51c8a879-5c4f-4e77-a39c-b22b107ccb85) |
| `CREATE-FAILED` (not sure how to trigger; perhaps an invalid cluster parameter?) | I suspect AWS will throw |
| `MODIFYING` (triggered via changing access control group) | Success |

The AWS console doesn't display an error on the "Tags" tab of a serverless cluster, but the network request it makes results in a 400 status code.
<img width="1920" alt="console" src="https://github.com/user-attachments/assets/e3354b44-06f3-4a11-9cab-d71c9d6325ec">
So `AVAILABLE` and `MODIFYING` appear to be the only valid statuses the tags can be queried in.
Odd behavior from AWS...

2024-08-30 18:23 UTC, Petersoj commented
@ekristen thoughts?

2024-08-30 19:58 UTC, ekristen commented
@Petersoj this is great, thank you. I've been pretty swamped this week, looking to come back around to this this weekend.

2024-08-30 20:10 UTC, Petersoj commented
Ok awesome. No rush. Thanks!

2024-08-31 22:57 UTC, ekristen commented
@Petersoj I've pushed my changes. Please take a look and test it out, let me know if you run into problems.

2024-08-31 23:13 UTC, Petersoj commented
Just tested it and it works great. Thanks!

2024-08-31 23:53 UTC, ekristen approved these changes

2024-08-31 23:54 UTC, merged

2024-08-31 23:56 UTC, ekristen commented
:tada: This issue has been resolved in version 3.17.0 :tada:

The release is available on [GitHub release](https://github.com/ekristen/aws-nuke/releases/tag/v3.17.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: