feat(bedrockagent): add agent, prompt, datasource and knowledge base
ekristen/aws-nuke pull request #427
Opened 2024-11-21 23:45 UTC by npellegrin

Closes #425

2024-11-21 23:46 UTC, npellegrin commented
New resources:

 - BedrockAgent
 - BedrockDataSource
 - BedrockKnowledgeBase
 - BedrockPrompt

Scan with feature activated

```
us-east-1 - BedrockAgent - AQSNLDAAXY - [ID: "AQSNLDAAXY", Name: "agent-quick-start-6j13n", Status: "NOT_PREPARED"] - would remove
us-east-1 - BedrockKnowledgeBase - OHVCRR2RER - [ID: "OHVCRR2RER", Name: "knowledge-base-quick-start-ntzce", Status: "ACTIVE"] - would remove
us-east-1 - BedrockPrompt - ENA3KYO939 - [ID: "ENA3KYO939", Name: "test", Version: "DRAFT"] - would remove
us-east-1 - BedrockDataSource - FTVCXNEISG - [ID: "FTVCXNEISG", KnowledgeBaseID: "OHVCRR2RER", Name: "knowledge-base-quick-start-jbqrq-data-source", Status: "AVAILABLE"] - would remove
```

Nuke with feature activated

```
us-east-1 - BedrockAgent - AQSNLDAAXY - [ID: "AQSNLDAAXY", Name: "agent-quick-start-6j13n", Status: "NOT_PREPARED"] - triggered remove
us-east-1 - BedrockKnowledgeBase - OHVCRR2RER - [ID: "OHVCRR2RER", Name: "knowledge-base-quick-start-ntzce", Status: "ACTIVE"] - triggered remove
us-east-1 - BedrockPrompt - ENA3KYO939 - [ID: "ENA3KYO939", Name: "test", Version: "DRAFT"] - triggered remove
us-east-1 - BedrockDataSource - FTVCXNEISG - [ID: "FTVCXNEISG", KnowledgeBaseID: "OHVCRR2RER", Name: "knowledge-base-quick-start-jbqrq-data-source", Status: "AVAILABLE"] - triggered remove

Removal requested: 3 waiting, 1 failed, 0 skipped, 0 finished

us-east-1 - BedrockAgent - AQSNLDAAXY - [ID: "AQSNLDAAXY", Name: "agent-quick-start-6j13n", Status: "NOT_PREPARED"] - removed
us-east-1 - BedrockKnowledgeBase - OHVCRR2RER - [ID: "OHVCRR2RER", Name: "knowledge-base-quick-start-ntzce", Status: "ACTIVE"] - removed
us-east-1 - BedrockPrompt - ENA3KYO939 - [ID: "ENA3KYO939", Name: "test", Version: "DRAFT"] - removed
us-east-1 - BedrockDataSource - FTVCXNEISG - [ID: "FTVCXNEISG", KnowledgeBaseID: "OHVCRR2RER", Name: "knowledge-base-quick-start-jbqrq-data-source", Status: "AVAILABLE"] - removed

Removal requested: 0 waiting, 0 failed, 0 skipped, 4 finished
```

2024-11-22 21:12 UTC, ekristen requested changes

2024-11-22 21:12 UTC, ekristen commented on resources/bedrock-agent-datasource.go
> +
Please remove empty line.

2024-11-24 09:07 UTC, npellegrin commented on resources/bedrock-agent-datasource.go
> +
Done 👍

2024-11-24 16:12 UTC, ekristen approved these changes

2024-11-24 16:12 UTC, merged

2024-11-25 00:08 UTC, ekristen commented
:tada: This PR is included in version 3.32.0 :tada:

The release is available on [GitHub release](https://github.com/ekristen/aws-nuke/releases/tag/v3.32.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: